### ISSUE TITLE
MariaDB in README

### ISSUE THREAD

**Issue by robertsilen** [k3s-io/kine#300]
Any reason MariaDB is not mentioned in the list of databases in the [README](https://github.com/k3s-io/kine/blob/master/README.md)? Could it be added?

**Comment by brandond** [comment]
We're kinda just listing the  backend drivers that we support:
https://github.com/k3s-io/kine/blob/edd8f35371395a3b0c4ea229061f46807855bed7/pkg/endpoint/endpoint.go#L31-L37

Since there is no mariadb-specific driver, we don't call it out. If you wanted to open a PR to call it mysql/mariadb that would probably be accepted.

**Comment by robertsilen** [comment]
Thanks @brandond , makes sense, I opened PR https://github.com/k3s-io/kine/pull/303
