### ISSUE TITLE
How to use kine in a k8s environment where etcd has been configured

### ISSUE THREAD

**Issue by upczsh** [k3s-io/kine#314]
I am a newbie with kine. I want to know how to use kine to replace etcd in a k8s cluster that already has etcd. Can I use kine to solve the problem of etcd storage not exceeding 8GB?

**Comment by brandond** [comment]
There is no supported migration from etcd back to kine. If you're trying to use kine instead of etcd just to store more than 8gb of data, you probably need to go back to the drawing board and redesign something.

**Comment by JanHolger** [comment]
For anyone attempting to migrate an existing etcd cluster to kine, I've implemented a small python script that simply copies over all keys from the etcd cluster. https://gist.github.com/JanHolger/c2bcdba384ca48fb843005f7264b6896

!!! USE THIS AT YOUR OWN RISK !!!
As @brandond mentioned this is by no means supported by kine, neither can I fully guarantee that this works for your setup.

Known issues:
- It will not migrate leases, so you need to ensure that the apiserver is fully stopped and all leases have expired or been revoked. Otherwise you might end up with deadlocks or events not getting cleaned up.
- It will not preserve history/versioning of keys. Im not fully aware of the consequences this might have but to my understanding it should not cause problems if everything is properly shut down before.
