### ISSUE TITLE
Clarification on TTL Change Logic in logstructured.go

### ISSUE THREAD

**Issue by Yuyz0112** [k3s-io/kine#382]
Hi,

I am reviewing KINE’s code to understand its TTL implementation and came across the following snippet:
https://github.com/k3s-io/kine/blob/master/pkg/logstructured/logstructured.go#L338-L343

I noticed that the condition for entering the if block (TTL changed for key) is based on the value of `preEventKV.expiredAt` rather than `curEventKV.expiredAt`.

Could you please clarify why the comparison uses preEventKV.expiredAt instead of curEventKV.expiredAt? Wouldn’t it make more sense to use the current state (curEventKV) to determine if the TTL has changed during delete?

Thank you for your help!

**Comment by brandond** [comment]
Perhaps. With other changes from https://github.com/k3s-io/kine/pull/238 I'm not sure that this block is actually needed any longer.

The `DelayingQueue` interface does not allow delaying the processing of an entry; the scheduled time for a key to be dequeued is only updated if it would cause the entry to be processed SOONER, not later. Ref: 
https://github.com/kubernetes/client-go/blob/master/util/workqueue/delaying_queue.go#L347

`handleTTLEvents` always retrieves the most recent event from the map before calling `deleteTTLEvent` on it. If there has been a more recent update to the key, the delete will fail because the resourceVersion has changed, and the error path will be taken. I am not sure we need to check the current or previous expiration again here in `deleteTTLEvent`.

**Comment by Yuyz0112** [comment]
@brandond Thanks for the clarification! I also think this if-block is not needed anymore while reading the code, maybe leaving it here at this moment is ok. I'm going to close the issue.
